spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
  devtools.livereload.enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
server:
  port: 5000
url:
  defaultImg: https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F75e23316-b3e6-4448-9fde-5852b400262a%2Flogo.png?table=block&id=3d0197c1-37ec-43d1-8ff7-39b5b254a3c8&spaceId=05b6560f-4c34-4811-bdc3-c653ef40ed27&width=250&userId=3331006c-ef8a-445a-bef0-40006db0d6f7&cache=v2
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA3AQINQBE3UOGWJZG
      secret-key: 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
    s3:
      bucket: errandbucket
    stack:
      auto: false
logging.level.com.amazonaws.util.EC2MetadataUtils: error
daangn:
  app-auth: YWY3Y2U4MzE2NjE0NDc5M2JlNmFmYzcyMzkxOGQ3ZjM6ZTEwNDFjNjliYmIwNGY1OWE1YmY0MWU1ODQ1OWEyYjI=
  app-key: nTFXLscne1iZhg1biq2nzoCHUP20AqRkFBUyuaQz1Yc=
  oapi:
    neighbor-range: RANGE_2
test: false
token.secret: Dj@bWv5w-$m#kjNWe?y#

application:
  mixpanel:
    token: a26050d2615ddc400fdfc0d88cd3d3f3
admin:
  username: errand-admin
  password: kpxLzx[8j3~&Wqz>
---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  config:
    active:
      on-profile: local
