daangn:
  oapi.url: https://oapi.alpha.kr.karrotmarket.com
  open-api.url: https://openapi.alpha.kr.karrotmarket.com
spring.datasource.url: jdbc:mysql://errand.c8zwh9jcttzy.ap-northeast-2.rds.amazonaws.com/errand-dev
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
sentry:
  dsn: https://4cef7bbae56446619e0f58a765d4428a@o1045456.ingest.sentry.io/6020835
  traces-sample-rate: 1.0