daangn:
  oapi.url: https://oapi.alpha.kr.karrotmarket.com
  open-api.url: https://openapi.alpha.kr.karrotmarket.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rkdudmysql4_
    url: jdbc:mysql://localhost:3306/errand
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
sentry:
  dsn: https://8565941fe5ce48e1b4dcb8e8e9bb250a@o1046587.ingest.sentry.io/6039414
  traces-sample-rate: 1.0
  environment: local