daangn:
  oapi.url: https://oapi.alpha.kr.karrotmarket.com
  open-api.url: https://openapi.alpha.kr.karrotmarket.com
spring.datasource.url: jdbc:mysql://errand.c8zwh9jcttzy.ap-northeast-2.rds.amazonaws.com/errand-dev
spring:
  redis:
    port: 6379
    host: errand-dev-001.wbblt4.0001.apn2.cache.amazonaws.com
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2