oauth:
  oapi: https://oapi.alpha.kr.karrotmarket.com
  open-api: https://openapi.alpha.kr.karrotmarket.com
spring.datasource.url: jdbc:mysql://errand.c8zwh9jcttzy.ap-northeast-2.rds.amazonaws.com/errand-dev